defaults:
  - agent: td3
  - override hydra/launcher: joblib

# unsupervised exploration
expl_agent: proto
tag:
# task settings
task: point_mass_maze_reach_custom_goal
discount: 0.99
# train settings
num_grad_steps: 500000
log_every_steps: 1000
# eval
eval_every_steps: 10000
num_eval_episodes: 1
# dataset
replay_buffer_dir: ../../../datasets # make sure to update this if you change hydra run dir
replay_buffer_size: 1000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}
# misc
seed: 1
device: cuda
save_video: true
use_tb: false
use_wandb: false
goal: false
eval: false
distill: false
experiment: exp
path: /home/ubuntu/proto_explore/output/2022.08.02/130412_bc16_goal
path_expert: /home/ubuntu/buffer/proto_explore/models/16_goals/final


hydra:
  run:
    dir: ./output/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}${tag}    

  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${experiment}
    subdir: ${hydra.job.num} 
