defaults:
  - agent: td3
  - override hydra/launcher: submitit_local

# unsupervised exploration
expl_agent: proto
# task settings
task: walker_walk
discount: 0.99
# train settings
num_grad_steps: 500000
log_every_steps: 1000
# eval
eval_every_steps: 10000
num_eval_episodes: 10
# dataset
replay_buffer_dir: ../../../datasets # make sure to update this if you change hydra run dir
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
# misc
seed: 1
device: cuda
save_video: true
use_tb: false
use_wandb: false
goal: false
eval: false
distill: false

path: /home/ubuntu/buffer/proto_explore/models/pmm_top_right/
path_expert1: /home/ubuntu/buffer/proto_explore/models/pmm_top_right/agent499999.pth
path_expert2: /home/ubuntu/buffer/proto_explore/models/pmm_top_left/agent_499999.pth
path_expert3: /home/ubuntu/buffer/proto_explore/models/pmm_bottom_left/agent_499999.pth
path_expert4: /home/ubuntu/buffer/proto_explore/models/pmm_bottom_right/agent_499999.pth

hydra:
  run:
    dir: ./output/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
