defaults:
  - agent: ddpg
  - override hydra/launcher: submitit_slurm

# mode
reward_free: true
# task settings
domain: walker # primal task will be infered in runtime
task: point_mass_maze_reach_custom_goal
task_no_goal: point_mass_maze_reach_no_goal
obs_type: states # [states, pixels]
frame_stack: 3 # only works if obs_type=pixels
action_repeat: 2 # set to 2 for pixels
discount: .99
# train settings
num_train_frames: 2000010
num_seed_frames: 4000
# eval
eval: False
eval_every_frames: 200000
num_eval_episodes: 2
# snapshot
snapshots: [100000, 500000, 1000000, 2000000]
snapshot_dir: ../../../models/${obs_type}/${domain}/${agent.name}/${seed}
# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 4
nstep: ${agent.nstep}
update_encoder: true # should always be true for pre-training
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: false
use_wandb: false
goal: false
hybrid: false
hybrid_gc: false
hybrid_pct: .5 #0-1
batch_size: 1024
batch_size_gc: 1024
hidden_dim: 1024
update_gc: 2
replay_buffer_gc: 100000
lr: .0001
offline: False
uniform: False
second: False
curriculum: False
tmux_session: ???
intr_coef: 0
offline_online: False
test: False
init_state: False
gcsl: False
bottom_left: False
init_value: 2
film_gc: False
sample_proto: ???
switch_gc: False
load_encoder: False
load_proto: False
goal_queue_size: 10
const_init: True
reward_nn: True
reward_scores: False
reward_scores_dense: False
reward_euclid: False
pos_reward: True
neg_reward: False
eval_after_step: 990000
episode_length: 100
num_protos: 512
episode_reset_length: 500
stddev_schedule: .2
stddev_schedule2: .2
stddev_clip: .3
stddev_clip2: .3
use_closest_proto: True
proto_const_init: True
resample_goal: False
use_predictor: False
load_model: False
pred_dim: 128
feature_dim: 50
sl: False
proj_dim: 512
asym: False
# experiment
experiment: exp

path: /home/ubuntu/proto_explore/url_benchmark/models/eval_8_23_4
replay_dir: /home/ubuntu/proto_explore/url_benchmark/models/eval_8_23_4/buffer1/buffer_copy
replay_dir2: false

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 16
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 200
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_update${update_gc}_bs${batch_size_gc}_hidden${hidden_dim}_${experiment}/.slurm
