# @package agent
_target_: agent.ddpg1.DDPG1Agent
name: ddpg1
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
goal_shape: ???
goal: ???
update_every_steps: 2
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
critic2_target_tau: 0.01
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 512
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 256 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}
