# @package agent
_target_: agent.ddpg.DDPGAgent
name: ddpg
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
goal_shape: ???
update_every_steps: 2
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
critic2_target_tau: 0.01
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: ???
stddev_schedule: ???
stddev_clip: ???
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}
stddev_schedule2: ???
stddev_clip2: ???
sl: ???
encoder1: ???
encoder2: ???
encoder3: ???
encoder1_ant: ???
feature_dim_gc: ???
inv: ???
use_actor_trunk: ???
use_critic_trunk: ???
init_from_proto: False
init_from_ddpg: False
pretrained_feature_dim: 16
scale: ???
gym: ???
state_shape: ???

