# @package agent
<<<<<<< HEAD
_target_: agent.ddpg.DDPGAgent
name: ddpg
=======
_target_: agent.ddpg_encoder0.DDPGEncoder0Agent
name: ddpg_encoder0
>>>>>>> 9277f0cb6621de196e54a5761a53143fc4dc4b47
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
goal_shape: ???
goal: ???
update_every_steps: 2
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
critic2_target_tau: 0.01
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}
