# @package agent
_target_: agent.proto_film0.ProtoFilm0Agent
name: proto_film0
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
goal_shape: ???
goal: false
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
critic2_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: ???
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: ???
init_critic: true
pred_dim: 128
proj_dim: 512
num_protos: 512
tau: 0.1
topk: 3
queue_size: 2048
update_gc: ???
gc_only: ???
offline: ???
encoder_target_tau: 0.05
update_encoder: ${update_encoder}
